//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTQLBTL.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class NHANVIENs
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        [AllowHtml]
        public string DiaChi { get; set; }
        public string SoDT { get; set; }
        public int Tuoi { get; set; }
        public string MaCV { get; set; }
    }
}
