//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTQLBTL.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TINTUCs
    {
        public string ID { get; set; }
        public string TieuDe { get; set; }
        [AllowHtml]
        public string NoiDung { get; set; }
    }
}
