// <auto-generated />
namespace LTQLBTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creat_Table_DICHVU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat_Table_DICHVU));
        
        string IMigrationMetadata.Id
        {
            get { return "202103030037596_Creat_Table_DICHVU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
